@LibraryAPI_HostAddress = https://localhost:7233

POST {{LibraryAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "J.K.",
  "lastName": "Rowling"
}

###

POST {{LibraryAPI_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Harry Potter and the Philosopher's Stone",
  "isbn": "1111",
  "publicationDate": "1997-01-11",
  "copies": 2
}

###
POST {{LibraryAPI_HostAddress}}/api/bookauthor
Content-Type: application/json

{
  "bookId": 1,
  "authorId": 1
}

###

POST {{LibraryAPI_HostAddress}}/api/borrowers
Content-Type: application/json

{
  "firstName": "Ben",
  "lastName": "Väst",
  "streetAddress": "I",
  "city": "U",
  "country": "S",
  "phoneNumber": "080",
  "email": "it.se"
}

###

GET {{LibraryAPI_HostAddress}}/api/books

###


GET {{LibraryAPI_HostAddress}}/api/books/1

###


GET {{LibraryAPI_HostAddress}}/api/books/search/Harry 

###

POST {{LibraryAPI_HostAddress}}/api/borrowedbooks/borrowbook
Content-Type: application/json

{
  "bookId": 1,
  "borrowerId": 1
  
}

###


PATCH {{LibraryAPI_HostAddress}}/api/borrowedbooks/returnbook
Content-Type: application/json

{
  "bookId": 1,
  "borrowerId": 1,
  "borrowerRating": 5
}

###


DELETE {{LibraryAPI_HostAddress}}/api/borrowers/0

###


DELETE {{LibraryAPI_HostAddress}}/api/books/0

###

DELETE {{LibraryAPI_HostAddress}}/api/authors/0

###
