@LibraryAPI_HostAddress = https://localhost:7233

POST {{LibraryAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "J.K.",
  "lastName": "Rowling"
}

###
POST {{LibraryAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "Peter",
  "lastName": "Straub"
}

###
POST {{LibraryAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "Stephen",
  "lastName": "King"
}

###

POST {{LibraryAPI_HostAddress}}/api/authors
Content-Type: application/json

{
  "firstName": "Fyodor",
  "lastName": "Dostoevsky"
}

###

POST {{LibraryAPI_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Harry Potter and the Philosopher's Stone",
  "isbn": "1111",
  "publicationDate": "1997-01-11",
  "copies": 2
}

###
POST {{LibraryAPI_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "The Talisman",
  "isbn": "978-0-670-69199-9",
  "publicationDate": "1984-11-07",
  "copies": 1
}

###

POST {{LibraryAPI_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "Crime and Punishment",
  "isbn": "9780192833839",
  "publicationDate": "1866-12-01",
  "copies": 3
}

###
POST {{LibraryAPI_HostAddress}}/api/bookauthor
Content-Type: application/json

{
  "bookId": 1,
  "authorId": 1
}

###
POST {{LibraryAPI_HostAddress}}/api/bookauthor
Content-Type: application/json

{
  "bookId": 2,
  "authorId": 2
}

###
POST {{LibraryAPI_HostAddress}}/api/bookauthor
Content-Type: application/json

{
  "bookId": 2,
  "authorId": 3
}

###
POST {{LibraryAPI_HostAddress}}/api/bookauthor
Content-Type: application/json

{
  "bookId": 3,
  "authorId": 4
}

###

GET {{LibraryAPI_HostAddress}}/api/books

###

GET {{LibraryAPI_HostAddress}}/api/authors

###


POST {{LibraryAPI_HostAddress}}/api/borrowers
Content-Type: application/json

{
  "firstName": "Ben",
  "lastName": "Väst",
  "streetAddress": "I",
  "city": "U",
  "country": "S",
  "phoneNumber": "080",
  "email": "it.se"
}

###

POST {{LibraryAPI_HostAddress}}/api/borrowers
Content-Type: application/json

{
  "firstName": "Alex",
  "lastName": "H",
  "streetAddress": "KG",
  "city": "Upp",
  "country": "S",
  "phoneNumber": "070",
  "email": "alex.h@it.com"
}

###

GET {{LibraryAPI_HostAddress}}/api/books

###

GET {{LibraryAPI_HostAddress}}/api/books/3

###

GET {{LibraryAPI_HostAddress}}/api/books/search/Harry

###

GET {{LibraryAPI_HostAddress}}/api/borrowers

###

POST {{LibraryAPI_HostAddress}}/api/bookloans/borrowbook
Content-Type: application/json

{
  "bookId": 3,
  "borrowerId": 2
  
}

###

PATCH {{LibraryAPI_HostAddress}}/api/bookloans/returnbook
Content-Type: application/json

{
  "bookId": 3,
  "borrowerId": 2,
  "borrowerRating": 5
}

###


DELETE {{LibraryAPI_HostAddress}}/api/borrowers/1

###


DELETE {{LibraryAPI_HostAddress}}/api/books/1

###

DELETE {{LibraryAPI_HostAddress}}/api/authors/1

###

GET {{LibraryAPI_HostAddress}}/api/borrowers

###

GET {{LibraryAPI_HostAddress}}/api/books

###

GET {{LibraryAPI_HostAddress}}/api/authors

###


GET {{LibraryAPI_HostAddress}}/api/bookloans

###


GET {{LibraryAPI_HostAddress}}/api/authors/1

###


